package com.babylon.insurance.shared.encryption;

import com.babylon.insurance.shared.exception.EncryptionException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Arrays;

/**
 * AES-256-GCM implementation of {@link EncryptionPort}.
 *
 * <p>Security properties:
 * <ul>
 *   <li>Algorithm: AES/GCM/NoPadding</li>
 *   <li>IV: 12 bytes generated by {@link SecureRandom#getInstanceStrong()} per call</li>
 *   <li>Authentication tag: 128 bits</li>
 *   <li>Key: 32 bytes read from {@code BABYLON_ENCRYPTION_KEY} environment variable (Base64)</li>
 *   <li>Wire format: Base64(IV[12] || ciphertext_with_tag)</li>
 * </ul>
 *
 * <p>Neither plain-text nor cipher-text values are ever logged by this class.
 */
@Component
public class AesGcmEncryptionAdapter implements EncryptionPort {

    private static final String ALGORITHM    = "AES/GCM/NoPadding";
    private static final int    IV_LENGTH    = 12;
    private static final int    TAG_BITS     = 128;

    private final SecretKey secretKey;

    /**
     * Constructs the adapter and derives the AES key from the Base64-encoded
     * environment variable {@code BABYLON_ENCRYPTION_KEY}.
     *
     * @param base64Key 32-byte key encoded in Base64; must not be blank
     * @throws IllegalArgumentException if the key is absent or has wrong length
     */
    public AesGcmEncryptionAdapter(
            @Value("${babylon.encryption.key}") String base64Key) {

        if (base64Key == null || base64Key.isBlank()) {
            throw new IllegalArgumentException(
                    "BABYLON_ENCRYPTION_KEY must be set: a non-empty Base64-encoded 32-byte AES key");
        }
        byte[] keyBytes = Base64.getDecoder().decode(base64Key.trim());
        if (keyBytes.length != 32) {
            throw new IllegalArgumentException(
                    "BABYLON_ENCRYPTION_KEY must decode to exactly 32 bytes (AES-256); got " + keyBytes.length);
        }
        this.secretKey = new SecretKeySpec(keyBytes, "AES");
    }

    /**
     * {@inheritDoc}
     *
     * <p>A fresh 12-byte IV is generated for each call, ensuring that encrypting
     * the same value twice produces different ciphertexts.
     */
    @Override
    public String encrypt(String plaintext) {
        try {
            byte[] iv = generateIv();
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, new GCMParameterSpec(TAG_BITS, iv));
            byte[] ciphertext = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));

            byte[] payload = new byte[IV_LENGTH + ciphertext.length];
            System.arraycopy(iv, 0, payload, 0, IV_LENGTH);
            System.arraycopy(ciphertext, 0, payload, IV_LENGTH, ciphertext.length);

            return Base64.getEncoder().encodeToString(payload);
        } catch (Exception ex) {
            throw new EncryptionException("Error al cifrar el valor", ex);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String decrypt(String ciphertext) {
        try {
            byte[] payload = Base64.getDecoder().decode(ciphertext);
            byte[] iv           = Arrays.copyOfRange(payload, 0, IV_LENGTH);
            byte[] encryptedData = Arrays.copyOfRange(payload, IV_LENGTH, payload.length);

            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.DECRYPT_MODE, secretKey, new GCMParameterSpec(TAG_BITS, iv));
            byte[] plain = cipher.doFinal(encryptedData);

            return new String(plain, StandardCharsets.UTF_8);
        } catch (Exception ex) {
            throw new EncryptionException("Error al descifrar el valor", ex);
        }
    }

    // ── private helpers ───────────────────────────────────────────────────────

    private byte[] generateIv() {
        try {
            byte[] iv = new byte[IV_LENGTH];
            SecureRandom.getInstanceStrong().nextBytes(iv);
            return iv;
        } catch (Exception ex) {
            throw new EncryptionException("Error al generar el IV de cifrado", ex);
        }
    }
}
